baseURL = "https://muoz.dev/"
languageCode = "en"
title = "Antonio Muñoz"
theme = "soho"

DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5
ignoreErrors = ["error-missing-instagram-accesstoken"]

[params]
author = "Mu/oz"
description = "I can visualize my whole life through names of video games. Willing to put in the time and learn from others. Passionate gamer."
# gravatar = "soho@example.com"
images = ["images/costillas-carnivoras-loop.gif"]
profilePicture = "images/costillas-carnivoras-loop.gif"

# copyright = "Mu/oz"
# license = "CC BY-SA 4.0"
# licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = false
mainSections = ["portfolio"]

## Set custom theme color.
themeColor = "#2C2F64"

  ## Set as many as you want.
  
  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/amuoz"

  [[params.socialIcons]]
  icon = "fa-itch-io"
  title = "muoz.itch.io"
  url = "https://muoz.itch.io/"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/antonio-munoz-gallego/"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/SCmU_Oz"

[menu]

  [[menu.main]]
  name = "Portfolio"
  weight = 100
  identifier = "portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "Gnome guts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 400
  url = "/about/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4